name: docs

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    name: Build and generate documentation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]  # use oldest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout CyIpopt
        uses: actions/checkout@v5
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: test-environment
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
      - name: Install basic dependencies
        run: conda install -q -y cython jupyter_sphinx "jupyter_core<5" matplotlib numpy numpydoc pythreejs setuptools "sphinx<7" symjit sympy scipy
      - name: Test building documentation
        run: cd docs && make clean && make html && cd ..
