name: docs

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    name: Build and generate documentation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]  # use oldest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout CyIpopt
        uses: actions/checkout@v5
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: test-environment
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
      - name: Install basic dependencies
        run: conda install -q -y "cython=0.29.*" "jupyter_sphinx=0.3.*" "jupyter<1.1" "ipwidgets<8" "matplotlib-base=3.5.*" "numpy=1.21.*" "numpydoc=1.2.*" pythreejs setuptools "sphinx=4.3.*" symjit "sympy=1.9.*" "scipy=1.8.*"
      - name: Test building documentation
        run: cd docs && make clean && make html && cd ..
