name: docs

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    name: Build and generate documentation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]  # use oldest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout CyIpopt
        uses: actions/checkout@v6
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test-environment
          auto-update-conda: true
          channels: conda-forge
          conda-remove-defaults: "true"
          miniforge-version: latest
          python-version: ${{ matrix.python-version }}
      # Install latest versions possible with the oldest supported Python.
      - name: Install basic dependencies
        run: conda install -q -y cython jupyter jupyter_sphinx matplotlib-base numpy numpydoc pythreejs setuptools sphinx symjit sympy scipy
      - name: Test building documentation
        run: cd docs && make clean && make html && cd ..
