name: oldest

on:
  push:
    branches: master
  pull_request:
    branches: master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    name: Build and run tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-24.04"]
        python-version: ["3.10"]

    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: test-environment
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
      - name: Install basic dependencies
        run: |
          conda install -q -y coverage cython=0.29.* matplotlib=3.6.* packaging=24.* pytest pytest-cov numpy=1.26.* pythreejs sympy=1.12.* scipy=1.11.* "setuptools>=68.1.2,<70"
      - name: Test with pytest
        run: pytest -cov .
      - name: Test installation of PyDy
        run: python setup.py install
